version: '3.8'

services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_ENV=dev
      - APP_URL=http://localhost

      # Database Configuration
      - DB_TYPE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres  # Use the service name for Docker internal communication
      - DB_PORT=5432      # Standard PostgreSQL port
      - DB_DATABASE=mydatabase
      - DB_SYNC=false

      # JWT Authentication
      - JWT_SECRET_KEY=cdw7232hidwuy23232wefewfs1213
      - JWT_REFRESH_SECRET=cdw7232hidwuy23232wefewfs1213
      - JWT_EXPIRATION_TIME=1h
      - JWT_REFRESH_EXPIRATION_TIME=1d

      # Telegram Bot Token
      - TELEGRAM_BOT_TOKEN=7704950124:AAGw6pxOlut_-iWnc3ZJxEHx99yt67MaLUY
    networks:
      - nestjs-net
      
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Maps port 80 in the container to 8080 on the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nestjs-app
    networks:
      - nestjs-net


  postgres:
    container_name: postgres-container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nestjs-net

networks:
  nestjs-net:
    driver: bridge

volumes:
  postgres-data:
